#!app/bin/python3
"""Runs a linting pass over the configured Netbox instance."""
import argparse
import os
import sys

import org
import linter

parser = argparse.ArgumentParser(description='Netbox rule linter')
parser.add_argument('-o', dest='org', action='store', required=True,
                    help='what organization configuration to apply', choices=org.registry.keys())

args = parser.parse_args()


def main():
    """Linter application entry point."""
    myorg = org.registry[args.org]
    token = os.environ.get('NETBOX_TOKEN', None)
    if token is None:
        print('Please set NETBOX_TOKEN before running this script', file=sys.stderr)
        return 1
    netbox = myorg.netbox_api(token)
    rule_settings = myorg.rule_settings()
    issues = 0
    mylinter = linter.Linter(rule_settings)
    # Lint devices
    for idx, issue in enumerate(mylinter.lint(netbox.dcim.devices.all())):
        issues = idx+1
        print(issue)
    if issues:
        print('{} issues found 😱'.format(issues))
        return 2
    print('No issues found 😎')
    return 0


if __name__ == '__main__':
    sys.exit(main())
